# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Advance Upstream Forks

on:
  schedule:
    # Every hour
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  advance_llvm_project:
    name: "Advance llvm-project"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Pull from upstream
        run: |
          git remote add upstream https://github.com/llvm/llvm-project.git
          git pull --ff-only upstream main
      - name: Pushing changes
        run: |
          git push
